src/Entity/Pilote.php
<?php

namespace App\Entity;

use App\Repository\PiloteRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PiloteRepository::class)]
class Pilote
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column(length: 64)]
    private ?string $Prenom = null;

    #[ORM\ManyToOne(inversedBy: 'pilotes')]
    private ?Qualification $qualification = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPrénom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getQualification(): ?Qualification
    {
        return $this->qualification;
    }

    public function setQualification(?Qualification $qualification): self
    {
        $this->qualification = $qualification;

        return $this;
    }
}

src/Entity/Qualification.php
<?php

namespace App\Entity;

use App\Repository\QualificationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QualificationRepository::class)]
class Qualification
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 8)]
    private ?string $Code = null;

    #[ORM\Column(length: 64)]
    private ?string $Libelle = null;

    #[ORM\OneToMany(mappedBy: 'qualification', targetEntity: Pilote::class)]
    private Collection $pilotes;

    public function __construct()
    {
        $this->pilotes = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->Code;
    }

    public function setCode(string $Code): self
    {
        $this->Code = $Code;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    /**
     * @return Collection<int, Pilote>
     */
    public function getPilotes(): Collection
    {
        return $this->pilotes;
    }

    public function addPilote(Pilote $pilote): self
    {
        if (!$this->pilotes->contains($pilote)) {
            $this->pilotes->add($pilote);
            $pilote->setQualification($this);
        }

        return $this;
    }

    public function removePilote(Pilote $pilote): self
    {
        if ($this->pilotes->removeElement($pilote)) {
            // set the owning side to null (unless already changed)
            if ($pilote->getQualification() === $this) {
                $pilote->setQualification(null);
            }
        }

        return $this;
    }
}

src/Controller/PiloteController.php
<?php

namespace App\Controller;

use App\Entity\Pilote;
use App\Entity\Qualification;
use App\Repository\PiloteRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PiloteController extends AbstractController
{
    #[Route('/pilote', name: 'app_pilote')]
    public function index(PiloteRepository $repo): Response
    {
        return $this->render('pilote/index.html.twig', [
            'pilotes' => $repo->findAll(),
        ]);
    }

    #[Route('/pilote/add', name: 'pilote_add', methods: ['GET', 'POST'])]
    public function add(Request $request, PiloteRepository $piloteRepository): Response
    {
        $pilote = new Pilote();
        $form = $this->createForm(PiloteType::class, $pilote);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $piloteRepository->save($pilote, true);

            return $this->redirectToRoute('app_pilote');
        }

        return $this->render('form_pilote/index.html.twig', [
            'form' => $form->createView(),
            'titre' => 'Ajouter un pilote',
        ]);
    }

    #[Route('/pilote/edit/{id}', name: 'pilote_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Pilote $pilote, PiloteRepository $piloteRepository): Response
    {
        $form = $this->createForm(PiloteType::class, $pilote);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $piloteRepository->save($pilote, true);

            return $this->redirectToRoute('app_pilote');
        }

        return $this->render('form_pilote/index.html.twig', [
            'form' => $form->createView(),
            'titre' => 'Modifier un pilote',
        ]);
    }
    
    #[Route('/pilote/{id}', name: 'pilote_show', methods: ['GET'])]
    public function show(Pilote $pilote, Qualification $qualification): Response
    {
        return $this->render('pilote/show.html.twig', [
            'pilote' => $pilote,
            'qualification' => $qualification,
        ]);
    }

    #[Route('/pilote/delete/{id}', name: 'pilote_delete', methods: ['GET'])]
    public function delete(Pilote $pilote, PiloteRepository $piloteRepository): Response
    {
        $piloteRepository->remove($pilote, true);
        return $this->redirectToRoute('app_pilote');
    }
}

templates/pilote/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des pilotes{% endblock %}

{% block body %}

    <h1>Pilotes</h1>
    <table class="table align-middle">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Email</th>
                <th>Qualification</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pilote in pilotes %}
            <tr class="vertical-align">
                <td>{{ pilote.id }}</td>
                <td>{{ pilote.nom }}</td>
                <td>{{ pilote.prenom }}</td>
                <td>{{ pilote.email }}</td>
                <td>{{ pilote.qualification.libelle }}</td>
                <td>
                    <a href="{{ path('pilote_show', {'id': pilote.id}) }}" class="btn btn-primary">show</a>
                    <a href="{{ path('pilote_edit', {'id': pilote.id}) }}" class="btn btn-warning">edit</a>
                    <a href="{{ path('pilote_delete', {'id': pilote.id}) }}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan=\"3\">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pilote_add') }}" class="btn btn-primary mt-3">Ajouter un pilote</a>
{% endblock %}

templates/pilote/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Détails pilote{% endblock %}

{% block body %}
    
    <h1>Détails</h1>
    
    <p>ID : {{pilote.id}}</p>
    <p>Nom : {{pilote.nom}}</p>
    <p>Prénom : {{pilote.prenom}}</p>
    <p>E-mail : {{pilote.email}}</p>
    <p>Qualification : {{pilote.qualification.libelle}}</p>
    

    <div class="col-3">
        <a href="{{path('app_pilote')}}" class="btn btn-primary">Retour à la liste</a>
    </div>

{% endblock %}